user:
  #username 学号或者工号
  username: '161105024'
  #tellphone 电话号码
  tellphone: '15xxxxxxxx8'
  #address 地址，定位信息
  address: 中国xx省xx市xx县xx路
  #email 接受通知消息的邮箱
  email: 461009747@qq.com
  #school 学校全称
  school: 福州大学
  #lon 当前位置经度
  lon: '119.203149'
  #lat 当前位置纬度
  lat: '26.062701'
  #abnormalReason 反馈信息，不需要可不填
  abnormalReason: 在家
  #photo 签到照片，不需要可不填
  photo:
#今日校园相关配置
cpdaily:
  #附加信息组默认选项配置，没有可留空
  defaults:
    #附加信息组默认选项配置，按顺序，可留空
    - default:
        title: 晚检体温(必填)
        value: 小于37.3度
    - default:
        title: 是否有发热、咳嗽、乏力、呼吸困难等疑似症状(必填)
        value: 否
#邮箱相关配置
email:
  #是否使用原作者提供邮箱服务（1是，0否）
  isAuthor: 1
  #邮箱服务器 @yeah.net: smtp.yeah.net
  mail_host: smtp.yeah.net
  #163用户名
  mail_user: sdfdfesd
  #密码(部分邮箱为授权码) 
  mail_pass: GVARYOSKBONSBMFB
  #用于发送结果信息的邮箱
  sender: sdfdfesd@yeah.net